function st_struct=init_st_struct()

st_struct=struct('TS_comp',[],...
    'TS_uncomp',[],...
    'Target_range',[],...
    'Target_range_min',[],...
    'Target_range_max',[],...
    'idx_r',[],...
    'StandDev_Angles_Minor_Axis',[],...
    'StandDev_Angles_Major_Axis',[],...
    'Angle_minor_axis',[],...
    'Angle_major_axis',[],...
    'Ping_number',[],...
    'Time',[],...
    'nb_valid_targets',[],...
    'idx_target_lin',[],...
    'pulse_env_before_lin',[],...
    'pulse_env_after_lin',[],...
    'PulseLength_Normalized_PLDL',[],...
    'Transmitted_pulse_length',[],...
    'Heave',[],...
    'Roll',[],...
    'Pitch',[],...
    'Heading',[],...
    'Dist',[]);
end