function algo_vec=init_algos(r,name)

name_vec={'BottomDetection','BadPings','Denoise','SchoolDetection','SingleTarget','TrackTarget'};
algo_vec=[];

if nargin==1
    name=name_vec;
end


if nansum(strcmpi(name,'BottomDetection'))>0
    algo_vec=[algo_vec algo_cl('Name','BottomDetection','Varargin',struct(...
        'denoised',0,...
        'thr_bottom',-35,...
        'thr_echo',-12,...
        'shift_bot',0,...
        'r_min',r(2),...
        'r_max',r(end-1)))];
end

if nansum(strcmpi(name,'BadPings'))>0
    algo_vec=[algo_vec algo_cl('Name','BadPings','Varargin',struct(...
        'denoised',0,...
        'thr_bottom',-35,...
        'thr_echo',-12,...
        'r_min',r(2),...
        'r_max',r(end-1),...
        'shift_bot',0,...
        'BS_std',6,...
        'BS_std_bool',true,...
        'thr_spikes_Above',3,...
        'thr_spikes_Below',3,...
        'Above',true,...
        'Below',false,...
        'burst_removal',false))];
end
if nansum(strcmpi(name,'Denoise'))>0
    algo_vec=[algo_vec algo_cl('Name','Denoise','Varargin',struct(...
        'HorzFilt',50,...
        'VertFilt',10,...
        'NoiseThr',-125,...
        'SNRThr',10))];
end
if nansum(strcmpi(name,'SchoolDetection'))>0
    algo_vec=[algo_vec algo_cl('Name','SchoolDetection','Varargin',struct(...
        'Type','Sv',...
        'Sv_thr',-65,...
        'l_min_can',10,...
        'h_min_tot',20,...
        'h_min_can',10,...
        'l_min_tot',50,...
        'nb_min_sples',100,...
        'horz_link_max',5,...
        'vert_link_max',5))];
end
if nansum(strcmpi(name,'SingleTarget'))>0
    algo_vec=[algo_vec algo_cl('Name','SingleTarget','Varargin',struct(...
        'Type','Sp',...
        'TS_threshold',-65,...
        'PLDL',6,...
        'MinNormPL',0.6,...
        'MaxNormPL',1.5,...
        'MaxBeamComp',12,...
        'MaxStdMinAxisAngle',1,...
        'MaxStdMajAxisAngle',1))];
end
if nansum(strcmpi(name,'TrackTarget'))>0
    algo_vec=[algo_vec algo_cl('Name','TrackTarget','Varargin',struct(...
        'AlphaMajAxis',0.7,...
        'AlphaMinAxis',0.7,...
        'AlphaRange',0.7,...
        'BetaMajAxis',0.5,...
        'BetaMinAxis',0.5,...
        'BetaRange',0.5,...
        'ExcluDistMajAxis',1,...
        'ExcluDistMinAxis',1,...
        'ExcluDistRange',1,...
        'MaxStdMajorAxisAngle',1,...
        'MaxStdMinorAxisAngle',1,...
        'MissedPingExpMajAxis',5,...
        'MissedPingExpMinAxis',5,...
        'MissedPingExpRange',5,...
        'WeightMajAxis',20,...
        'WeightMinAxis',20,...
        'WeightRange',40,...
        'WeightTS',10,...
        'WeightPingGap',10,...
        'Min_ST_Track',8,...
        'Min_Pings_Track',10,...
        'Max_Gap_Track',5))];
end

end