%% update_algos.m
%
% TODO: write short description of function
%
%% Help
%
% *USE*
%
% TODO: write longer description of function
%
% *INPUT VARIABLES*
%
% * |main_figure|: TODO: write description and info on variable
%
% *OUTPUT VARIABLES*
%
% NA
%
% *RESEARCH NOTES*
%
% TODO: write research notes
%
% *NEW FEATURES*
%
% * 2017-03-28: header (Alex Schimel)
% * YYYY-MM-DD: first version (Yoann Ladroit)
%
% *EXAMPLE*
%
% TODO: write examples
%
% *AUTHOR, AFFILIATION & COPYRIGHT*
%
% Yoann Ladroit, NIWA. Type |help EchoAnalysis.m| for copyright information.

%% Function
function update_algos(main_figure)

layer=getappdata(main_figure,'Layer');

if isempty(layer)
return;
end
    
curr_disp=getappdata(main_figure,'Curr_disp');
idx_freq=find_freq_idx(layer,curr_disp.Freq);

trans_obj=layer.Transceivers(idx_freq);

bottom_tab_comp=getappdata(main_figure,'Bottom_tab');
bottom_tab_v2_comp=getappdata(main_figure,'Bottom_tab_v2');
bad_ping_tab_comp=getappdata(main_figure,'Bad_ping_tab');
school_detect_tab_comp=getappdata(main_figure,'School_detect_tab');
denoise_tab_comp=getappdata(main_figure,'Denoise_tab');
single_target_tab_comp=getappdata(main_figure,'Single_target_tab');

track_target_tab_comp=getappdata(main_figure,'Track_target_tab');



[idx_algo_denoise,found_denoise]=find_algo_idx(trans_obj,'Denoise');
[idx_algo_bot,found_bot]=find_algo_idx(trans_obj,'BottomDetection');
[idx_algo_bot_v2,found_bot_v2]=find_algo_idx(trans_obj,'BottomDetectionV2');
[idx_algo_bp,found_bp]=find_algo_idx(trans_obj,'BadPings');
[idx_school_detect,found_school]=find_algo_idx(trans_obj,'SchoolDetection');
[idx_single_target,found_single]=find_algo_idx(trans_obj,'SingleTarget');
[idx_track_target,found_track]=find_algo_idx(trans_obj,'TrackTarget');

if found_bot>0
    
    if strcmp(bottom_tab_comp.horz_filt.Enable,'on')
        horz_filt=str2double(get(bottom_tab_comp.horz_filt,'string'));
    else
        horz_filt=0;
    end
    trans_obj.Algo(idx_algo_bot).Varargin=struct(...
        'thr_bottom',str2double(get(bottom_tab_comp.thr_bottom,'string')),...
        'denoised',get(bottom_tab_comp.denoised,'value'),...
        'thr_backstep',str2double(get(bottom_tab_comp.thr_backstep,'string')),...
        'vert_filt',str2double(get(bottom_tab_comp.vert_filt,'string')),...
        'horz_filt',horz_filt,...
        'shift_bot',str2double(get(bottom_tab_comp.shift_bot,'string')),...
        'r_min',str2double(get(bottom_tab_comp.r_min,'string')),...
        'r_max',str2double(get(bottom_tab_comp.r_max,'string')),...
        'idx_r',[],...
        'idx_pings',[]);
end

if found_bot_v2>0
    trans_obj.Algo(idx_algo_bot_v2).Varargin=struct(...
         'thr_bottom',str2double(get(bottom_tab_v2_comp.thr_bottom,'string')),...
        'denoised',get(bottom_tab_v2_comp.denoised,'value'),...
        'thr_backstep',str2double(get(bottom_tab_v2_comp.thr_backstep,'string')),...
        'thr_echo',str2double(get(bottom_tab_v2_comp.thr_echo,'string')),...
       'thr_cum',str2double(get(bottom_tab_v2_comp.thr_cum,'string')),...
        'shift_bot',str2double(get(bottom_tab_v2_comp.shift_bot,'string')),...
        'r_min',str2double(get(bottom_tab_v2_comp.r_min,'string')),...
        'r_max',str2double(get(bottom_tab_v2_comp.r_max,'string')),...
        'idx_r',[],...
        'idx_pings',[]);  
end

if found_bp>0
    bot_vers=get(bad_ping_tab_comp.version,'String');
    bot_ver=bot_vers{get(bad_ping_tab_comp.version,'Value')};
    switch bot_ver
        case'V1'
            bad_ping_tab_bot=bottom_tab_comp;
              
        otherwise
            bad_ping_tab_bot=bottom_tab_v2_comp;

    end
    trans_obj.Algo(idx_algo_bp).Varargin=struct(...
        'thr_bottom',str2double(get(bad_ping_tab_bot.thr_bottom,'string')),...
        'denoised',get(bad_ping_tab_bot.denoised,'value'),...
        'thr_backstep',str2double(get(bad_ping_tab_bot.thr_backstep,'string')),...
        'vert_filt',str2double(get(bottom_tab_comp.vert_filt,'string')),...
        'shift_bot',str2double(get(bad_ping_tab_bot.shift_bot,'string')),...
        'r_min',str2double(get(bad_ping_tab_bot.r_min,'string')),...
        'r_max',str2double(get(bad_ping_tab_bot.r_max,'string')),...
        'horz_filt',horz_filt,...
        'botDetecVer',bot_ver,...
        'thr_echo',str2double(get(bottom_tab_v2_comp.thr_echo,'string')),...
        'thr_cum',str2double(get(bottom_tab_v2_comp.thr_cum,'string')),...
        'BS_std',str2double(get(bad_ping_tab_comp.BS_std,'string')),...
        'BS_std_bool',get(bad_ping_tab_comp.BS_std_bool,'Value')==1,...
        'thr_spikes_Above',str2double(get(bad_ping_tab_comp.thr_spikes_Above,'string')),...
        'thr_spikes_Below',str2double(get(bad_ping_tab_comp.thr_spikes_Below,'string')),...
        'Above',get(bad_ping_tab_comp.Above,'Value')==1,...
        'Below',get(bad_ping_tab_comp.Below,'Value')==1); 
 end


if found_school>0
    if get(bottom_tab_comp.denoised,'Value')>0
        Type='svdenoised';
    else
        Type='sv';
    end
    trans_obj.Algo(idx_school_detect).Varargin=struct(...
        'Type',Type,....
        'Sv_thr',str2double(get(school_detect_tab_comp.Sv_thr,'String')),...
        'l_min_can',str2double(get(school_detect_tab_comp.l_min_can,'String')),...
        'h_min_tot',str2double(get(school_detect_tab_comp.h_min_tot,'String')),...
        'h_min_can',str2double(get(school_detect_tab_comp.h_min_can,'String')),...
        'l_min_tot',str2double(get(school_detect_tab_comp.l_min_tot,'String')),...
        'nb_min_sples',str2double(get(school_detect_tab_comp.nb_min_sples,'String')),...
        'horz_link_max',str2double(get(school_detect_tab_comp.horz_link_max,'String')),...
        'vert_link_max',str2double(get(school_detect_tab_comp.vert_link_max,'String')),...
        'depth_max',Inf,...
        'idx_r',[],...
        'idx_pings',[]);
end



if found_denoise>0
    trans_obj.Algo(idx_algo_denoise).Varargin=struct(...
        'SNRThr',round(str2double(get(denoise_tab_comp.SNRThr,'string'))),...
        'HorzFilt',round(str2double(get(denoise_tab_comp.HorzFilt,'string'))),...
        'VertFilt',str2double(get(denoise_tab_comp.VertFilt,'string')),...
        'NoiseThr',round(str2double(get(denoise_tab_comp.NoiseThr,'string'))));
end

if found_single>0
    if isfield(bottom_tab_comp,'denoised')
        if get(bottom_tab_comp.denoised,'Value')>0
            Type='spdenoised';
        else
            Type='spdenoised';
        end
    else
        Type='spdenoised';
    end
    
    trans_obj.Algo(idx_single_target).Varargin=struct(...
        'Type',Type,...
        'TS_threshold',str2double(get(single_target_tab_comp.TS_threshold,'string')),...
        'PLDL',str2double(get(single_target_tab_comp.PLDL,'string')),...
        'MinNormPL',str2double(get(single_target_tab_comp.MinNormPL,'string')),...
        'MaxNormPL',str2double(get(single_target_tab_comp.MaxNormPL,'string')),...
        'MaxBeamComp',str2double(get(single_target_tab_comp.MaxBeamComp,'string')),...
        'MaxStdMinAxisAngle',str2double(get(single_target_tab_comp.MaxStdMinAxisAngle,'string')),...
        'MaxStdMajAxisAngle',str2double(get(single_target_tab_comp.MaxStdMajAxisAngle,'string')),...
        'idx_r',[],...
        'idx_pings',[]);
end

if found_track
trans_obj.Algo(idx_track_target).Varargin=struct(...
        'AlphaMajAxis',str2double(get(track_target_tab_comp.AlphaMajAxis,'string')),...
        'AlphaMinAxis',str2double(get(track_target_tab_comp.AlphaMinAxis,'string')),...
        'AlphaRange',str2double(get(track_target_tab_comp.AlphaRange,'string')),...
        'BetaMajAxis',str2double(get(track_target_tab_comp.BetaMajAxis,'string')),...
        'BetaMinAxis',str2double(get(track_target_tab_comp.BetaMinAxis,'string')),...
        'BetaRange',str2double(get(track_target_tab_comp.BetaRange,'string')),...
        'ExcluDistMajAxis',str2double(get(track_target_tab_comp.ExcluDistMajAxis,'string')),...
        'ExcluDistMinAxis',str2double(get(track_target_tab_comp.ExcluDistMinAxis,'string')),...
        'ExcluDistRange',str2double(get(track_target_tab_comp.ExcluDistRange,'string')),...
        'MaxStdMinorAxisAngle',str2double(get(track_target_tab_comp.MaxStdMinorAxisAngle,'string')),...
        'MaxStdMajorAxisAngle',str2double(get(track_target_tab_comp.MaxStdMajorAxisAngle,'string')),...
        'MissedPingExpMajAxis',str2double(get(track_target_tab_comp.MissedPingExpMajAxis,'string')),...
        'MissedPingExpMinAxis',str2double(get(track_target_tab_comp.MissedPingExpMinAxis,'string')),...
        'MissedPingExpRange',str2double(get(track_target_tab_comp.MissedPingExpRange,'string')),...
        'WeightMajAxis',str2double(get(track_target_tab_comp.WeightMajAxis,'string')),...
        'WeightMinAxis',str2double(get(track_target_tab_comp.WeightMinAxis,'string')),...
        'WeightRange',str2double(get(track_target_tab_comp.WeightRange,'string')),...
        'WeightTS',str2double(get(track_target_tab_comp.WeightTS,'string')),...
        'WeightPingGap',str2double(get(track_target_tab_comp.WeightPingGap,'string')),...
        'Min_ST_Track',str2double(get(track_target_tab_comp.Min_ST_Track,'string')),...
        'Min_Pings_Track',str2double(get(track_target_tab_comp.Min_Pings_Track,'string')),...
        'Max_Gap_Track',str2double(get(track_target_tab_comp.Max_Gap_Track,'string')));
end
    
    
setappdata(main_figure,'Layer',layer);


end