function update_algos(main_figure)

layer=getappdata(main_figure,'Layer');

if isempty(layer)
return;
end
    
curr_disp=getappdata(main_figure,'Curr_disp');
idx_freq=find_freq_idx(layer,curr_disp.Freq);

trans_obj=layer.Transceivers(idx_freq);

bottom_tab_comp=getappdata(main_figure,'Bottom_tab');
bottom_tab_v2_comp=getappdata(main_figure,'Bottom_tab_v2');
bad_ping_tab_comp=getappdata(main_figure,'Bad_ping_tab');
school_detect_tab_comp=getappdata(main_figure,'School_detect_tab');
denoise_tab_comp=getappdata(main_figure,'Denoise_tab');
single_target_tab_comp=getappdata(main_figure,'Single_target_tab');

track_target_tab_comp=getappdata(main_figure,'Track_target_tab');



[idx_algo_denoise,found_denoise]=find_algo_idx(trans_obj,'Denoise');
[idx_algo_bot,found_bot]=find_algo_idx(trans_obj,'BottomDetection');
[idx_algo_bot_v2,found_bot_v2]=find_algo_idx(trans_obj,'BottomDetectionV2');
[idx_algo_bp,found_bp]=find_algo_idx(trans_obj,'BadPings');
[idx_school_detect,found_school]=find_algo_idx(trans_obj,'SchoolDetection');
[idx_single_target,found_single]=find_algo_idx(trans_obj,'SingleTarget');
[idx_track_target,found_track]=find_algo_idx(trans_obj,'TrackTarget');

if found_bot>0
    
    if strcmp(bottom_tab_comp.horz_filt_sl.Enable,'on')
        horz_filt=get(bottom_tab_comp.horz_filt_sl,'Value');
    else
        horz_filt=0;
    end
    trans_obj.Algo(idx_algo_bot).Varargin=struct(...
        'thr_bottom',get(bottom_tab_comp.Thr_bottom_sl,'Value'),...
        'denoised',get(bottom_tab_comp.denoised,'Value'),...
        'thr_backstep',get(bottom_tab_comp.Thr_backstep_sl,'Value'),...
        'vert_filt',get(bottom_tab_comp.vert_filt_sl,'Value'),...
        'horz_filt',horz_filt,...
        'shift_bot',get(bottom_tab_comp.Shift_bot_sl,'Value'),...
        'r_min',get(bottom_tab_comp.r_min_sl,'Value'),...
        'r_max',get(bottom_tab_comp.r_max_sl,'Value'));
end

if found_bp>0
    bot_vers=get(bad_ping_tab_comp.version,'String');
    bot_ver=bot_vers{get(bad_ping_tab_comp.version,'Value')};
    switch bot_ver
        case'V1'
            bad_ping_tab_bot=bottom_tab_comp;
        otherwise
            bad_ping_tab_bot=bottom_tab_v2_comp;
    end
    
    trans_obj.Algo(idx_algo_bp).Varargin=struct(...
        'thr_bottom',get(bad_ping_tab_bot.Thr_bottom_sl,'Value'),...
        'denoised',get(bad_ping_tab_bot.denoised,'Value'),...
        'thr_backstep',get(bad_ping_tab_bot.Thr_backstep_sl,'Value'),...
        'vert_filt',get(bottom_tab_comp.vert_filt_sl,'Value'),...
        'horz_filt',horz_filt,...
        'botDetecVer',bot_ver,...
        'shift_bot',get(bad_ping_tab_bot.Shift_bot_sl,'Value'),...
        'r_min',get(bad_ping_tab_bot.r_min_sl,'Value'),...
        'r_max',get(bad_ping_tab_bot.r_max_sl,'Value'),...
        'BS_std',get(bad_ping_tab_comp.BS_std_sl,'Value'),...
        'BS_std_bool',get(bad_ping_tab_comp.BS_std_bool,'Value')==1,...
        'thr_spikes_Above',get(bad_ping_tab_comp.thr_spikes_Above_sl,'Value'),...
        'thr_spikes_Below',get(bad_ping_tab_comp.thr_spikes_Below_sl,'Value'),...
        'Above',get(bad_ping_tab_comp.Above,'Value')==1,...
        'Below',get(bad_ping_tab_comp.Below,'Value')==1);
end

if found_bot_v2>0
    trans_obj.Algo(idx_algo_bot_v2).Varargin=struct(...
        'thr_bottom',get(bottom_tab_v2_comp.Thr_bottom_sl,'Value'),...
        'denoised',get(bottom_tab_v2_comp.denoised,'Value'),...
        'thr_backstep',get(bottom_tab_v2_comp.Thr_backstep_sl,'Value'),...
        'shift_bot',get(bottom_tab_v2_comp.Shift_bot_sl,'Value'),...
        'r_min',get(bottom_tab_v2_comp.r_min_sl,'Value'),...
        'r_max',get(bottom_tab_v2_comp.r_max_sl,'Value'));  
end

if found_school>0
    if get(bottom_tab_comp.denoised,'Value')>0
        Type='svdenoised';
    else
        Type='sv';
    end
    trans_obj.Algo(idx_school_detect).Varargin=struct(...
        'Type',Type,....
        'Sv_thr',get(school_detect_tab_comp.sv_thr_sl,'Value'),...
        'l_min_can',get(school_detect_tab_comp.l_min_can_sl,'Value'),...
        'h_min_tot',get(school_detect_tab_comp.h_min_tot_sl,'Value'),...
        'h_min_can',get(school_detect_tab_comp.h_min_can_sl,'Value'),...
        'l_min_tot',get(school_detect_tab_comp.l_min_tot_sl,'Value'),...
        'nb_min_sples',get(school_detect_tab_comp.nb_min_sples_sl,'Value'),...
        'horz_link_max',get(school_detect_tab_comp.horz_link_max_sl,'Value'),...
        'vert_link_max',get(school_detect_tab_comp.vert_link_max_sl,'Value'),...
        'depth_max',Inf);
end



if found_denoise>0
    trans_obj.Algo(idx_algo_denoise).Varargin=struct(...
        'SNRThr',round(get(denoise_tab_comp.SNRThr_sl,'Value')),...
        'HorzFilt',round(get(denoise_tab_comp.HorzFilt_sl,'Value')),...
        'VertFilt',get(denoise_tab_comp.VertFilt_sl,'Value'),...
        'NoiseThr',round(get(denoise_tab_comp.NoiseThr_sl,'Value')));
end

if found_single>0
    if isfield(bottom_tab_comp,'denoised')
        if get(bottom_tab_comp.denoised,'Value')>0
            Type='spdenoised';
        else
            Type='spdenoised';
        end
    else
        Type='spdenoised';
    end
    
    trans_obj.Algo(idx_single_target).Varargin=struct(...
        'Type',Type,...
        'TS_threshold',get(single_target_tab_comp.TS_threshold_sl,'Value'),...
        'PLDL',get(single_target_tab_comp.PLDL_sl,'Value'),...
        'MinNormPL',get(single_target_tab_comp.MinNormPL_sl,'Value'),...
        'MaxNormPL',get(single_target_tab_comp.MaxNormPL_sl,'Value'),...
        'MaxBeamComp',get(single_target_tab_comp.MaxBeamComp_sl,'Value'),...
        'MaxStdMinAxisAngle',get(single_target_tab_comp.MaxStdMinAxisAngle_sl,'Value'),...
        'MaxStdMajAxisAngle',get(single_target_tab_comp.MaxStdMajAxisAngle_sl,'Value'));
end

if found_track
trans_obj.Algo(idx_track_target).Varargin=struct(...
        'AlphaMajAxis',str2double(get(track_target_tab_comp.AlphaMajAxis,'string')),...
        'AlphaMinAxis',str2double(get(track_target_tab_comp.AlphaMinAxis,'string')),...
        'AlphaRange',str2double(get(track_target_tab_comp.AlphaRange,'string')),...
        'BetaMajAxis',str2double(get(track_target_tab_comp.BetaMajAxis,'string')),...
        'BetaMinAxis',str2double(get(track_target_tab_comp.BetaMinAxis,'string')),...
        'BetaRange',str2double(get(track_target_tab_comp.BetaRange,'string')),...
        'ExcluDistMajAxis',str2double(get(track_target_tab_comp.ExcluDistMajAxis,'string')),...
        'ExcluDistMinAxis',str2double(get(track_target_tab_comp.ExcluDistMinAxis,'string')),...
        'ExcluDistRange',str2double(get(track_target_tab_comp.ExcluDistRange,'string')),...
        'MaxStdMinorAxisAngle',str2double(get(track_target_tab_comp.MaxStdMinorAxisAngle,'string')),...
        'MaxStdMajorAxisAngle',str2double(get(track_target_tab_comp.MaxStdMajorAxisAngle,'string')),...
        'MissedPingExpMajAxis',str2double(get(track_target_tab_comp.MissedPingExpMajAxis,'string')),...
        'MissedPingExpMinAxis',str2double(get(track_target_tab_comp.MissedPingExpMinAxis,'string')),...
        'MissedPingExpRange',str2double(get(track_target_tab_comp.MissedPingExpRange,'string')),...
        'WeightMajAxis',str2double(get(track_target_tab_comp.WeightMajAxis,'string')),...
        'WeightMinAxis',str2double(get(track_target_tab_comp.WeightMinAxis,'string')),...
        'WeightRange',str2double(get(track_target_tab_comp.WeightRange,'string')),...
        'WeightTS',str2double(get(track_target_tab_comp.WeightTS,'string')),...
        'WeightPingGap',str2double(get(track_target_tab_comp.WeightPingGap,'string')),...
        'Min_ST_Track',str2double(get(track_target_tab_comp.Min_ST_Track,'string')),...
        'Min_Pings_Track',str2double(get(track_target_tab_comp.Min_Pings_Track,'string')),...
        'Max_Gap_Track',str2double(get(track_target_tab_comp.Max_Gap_Track,'string')));
end
    
    
setappdata(main_figure,'Layer',layer);


end