function ship_struct=init_ship_struct(ship_type_key)

ship_struct=struct(....
	'ship_type_key',ship_type_key,...
    'ship_name','',...
	'ship_code','',...
	'ship_platform_code','',...	
	'ship_platform_class','',...
	'ship_callsign','',...
	'ship_alt_callsign','',...
	'ship_IMO','',...
	'ship_operator','',...	
	'ship_length',0,...		
	'ship_breadth',0,...	
	'ship_tonnage',0,...
    'ship_draft',0,...
	'ship_engine_power',0,...	
	'ship_noise_design','unknown',...	
	'ship_aknowledgement','',...
	'ship_comments','');	
	
end