% CREATE TABLE t_mission
% (
% 	mission_pkey 			SERIAL PRIMARY KEY,
% 	
% 	mission_name 			TEXT, 		-- Name of mission (ICES mission_name)
% 	mission_abstract 		TEXT, 		-- Text description of the mission, its purpose, scientific objectives and area of operation (ICES mission_abstract)
% 	mission_start_date 		TIMESTAMP,	-- Start date and time of the mission (ICES mission_start_date)
% 	mission_end_date 		TIMESTAMP,	-- End date and time of the mission (ICES mission_end_date)
% 	principal_investigator 		TEXT,		-- Name of the principal investigator in charge of the mission (ICES principal_investigator)
% 	principal_investigator_email	TEXT,		-- Principal investigator e-mail address (ICES principal_investigator_email)
% 	institution 			TEXT,		-- Name of the institute, facility, or company where the original data were produced (ICES institution)
% 	data_centre 			TEXT,		-- Data centre in charge of the data management or party who distributed the resource (ICES data_centre)
% 	data_centre_email 		TEXT,		-- Data centre contact e-mail address (ICES data_centre_email)
% 	mission_id			TEXT, 		-- ID code of mission (ICES mission_id) 
% 	creator				TEXT,		-- Entity primarily responsible for making the resource (ICES creator)
% 	contributor			TEXT,		-- Entity responsible for making contributions to the resource (ICES contributor)
% 	
% 	mission_comments		TEXT		-- Free text fields for relevant information not captured by other attributes (ICES mission_comments)
% );
% COMMENT ON TABLE t_mission is 'Mission or projects for which acoustic data were collected.';

function mission_struct=init_mission_struct()

mission_struct=struct(...
    'mission_name','',...
    'mission_abstract','',...
    'mission_start_date',now,...
    'mission_end_date',now,...
    'principal_investigator','',...
    'principal_investigator_email','',...
    'institution','',...
    'data_centre','',...
    'data_centre_email','',...
    'mission_id','',...
    'creator','',...
    'contributor','',...
    'mission_comments','');
end