function initialize_reg_bot_db(dbfile)

if exist(dbfile,'file')==2
    warning('Region and Bottom db file %s already exists, if you want to reinitialize it, delete it manually',dbfile);
    return;   
end

[dbdir,~]=fileparts(dbfile);
if exist(dbdir,'dir')==0
    mkdir(dbdir);
end

dbconn=sqlite(dbfile,'create');

createbotTable = ['create table bottom ' ...
    '(Filename VARCHAR DEFAULT NULL,'...
    'Version INTEGER DEFAULT 1,'...
    'Bot_XML TEXT DEFAULT NULL,'...
    'Save_time TIME DEFAULT CURRENT_TIMESTAMP,'...
    'Comment TEXT DEFAULT "",'...
    'PRIMARY KEY(Filename,version)'...
    'ON CONFLICT ABORT)'];

createregTable = ['create table region ' ...
    '(Filename VARCHAR DEFAULT NULL,'...
    'Version NUMERIC DEFAULT 1,'...
    'Reg_XML TEXT DEFAULT NULL,'...
    'Save_time TIME DEFAULT CURRENT_TIMESTAMP,'...
    'Comment TEXT DEFAULT "",'...
    'PRIMARY KEY(Filename,version)'...
    'ON CONFLICT ABORT)'];

dbconn.exec(createbotTable);
dbconn.exec(createregTable);

close(dbconn);