function help_menu(~,~,main_figure)
import java.awt.Color;
dialog_fig=new_echo_figure(main_figure,...
    'Units','pixels','Position',[500 300 400 400],...                                      
    'Name','Shortcuts',...  
    'Resize','on',...
    'MenuBar','none',...
    'Tag','shortcuts');

labelStr = ['<html><ul>Shortcuts:'...
    '<li><i>1</i> : Zoom In (right click for vertical zoom)</li>'...
    '<li><i>Shift+1</i> : Zoom Out (right click for zoom all)</li>'...
    '<li><i>Mouse Scroll</i> : Zoom In/Out</li>'...
    '<li><i>2</i> : Mark bad transmit</li>'...
    '<li><i>3</i> : Edit Bottom</li>'...
    '<li><i>4</i> : Create Region</li>'...
    '<li><i>Delete</i> : Delete active region Region</li>'...
    '<li><i>b</i> : Toggle Under bottom display</li>'...
    '<li><i>r</i> : Toggle Region display</li>'...
    '<li><i>t</i> : Toggle Bad Transmit display</li>'...
    '<li><i>f</i> : Change Frequency</li>'...
    '<li><i>e</i> : Change Data displayed</li>'...
    '<li><i>n</i> : Next Layer</li>'...
    '<li><i>p</i> : Previous Layer</li>'...
    '<li><i>+</i> : Increase CLim</li>'...
    '<li><i>-</i> : Decrease CLim</li>'...
    '<li><i>l</i> : Display/Edit Logbook</li>'...
    '</ul>'...
    '<ul>Tips:'...
    '<li>Most objects (lines, regions, echogramms...) have a context menu associated to them. Right-click and see!</li>'
    '<li>You can grab the Mini Axes window by its side and drag it out</li>'...
    '<li>You can draw a zoom window in the mini axes, and drag it around...</li>'...
    '</ul></html>'];
jLabel = javaObjectEDT('javax.swing.JLabel',labelStr);
[jcomp,~] = javacomponent(jLabel,[0,0,400,400],dialog_fig);
jcomp.setBackground(Color.WHITE);
format_color_gui(dialog_fig);

end