function shortcut_menu(~,~,main_figure)

curr_disp=getappdata(main_figure,'Curr_disp');
dialog_fig=new_echo_figure(main_figure,...
    'Units','pixels','Position',[500 100 500 800],...                                      
    'Name','Shortcuts',...  
    'Resize','off',...
    'Tag','shortcuts',...
    'visible','off');

labelStr = ['<html><ul>Shortcuts:'...
    '<li><i>0</i> :Nornmal Mode</li>'...
    '<li><i>1</i> : Zoom In (right click for vertical zoom)</li>'...
    '<li><i>Shift+1</i> : Zoom Out (right click for zoom all)</li>'...
    '<li><i>2</i> : Bad Transmit Mode</li>'...
    '<li><i>3</i> : Edit Bottom Mode</li>'...
    '<li><i>4</i> : Create Region Mode</li>'...
    '<li><i>5</i> : Measure Mode</li>'...
    '<li><i>Mouse Scroll</i> : Zoom In/Out</li>'...
    '<li><i>w/s</i> : Zoom In/out</li>'...
    '<li><i>a/d</i> : Move left/right</li>'...
    '<li><i>Arrow Keys</i> : Move around echogram</li>'...
    '<li><i>Delete</i> : Delete active region Region</li>'...
    '<li><i>b</i> : Toggle Under bottom display</li>'...
    '<li><i>r</i> : Toggle Region display</li>'...
    '<li><i>t</i> : Toggle Bad Transmit display</li>'...
    '<li><i>f</i> : Change Frequency</li>'...
    '<li><i>e</i> : Change Data displayed</li>'...
    '<li><i>n</i> : Next Layer</li>'...
    '<li><i>p</i> : Previous Layer</li>'...
    '<li><i>+</i> : Increase CLim</li>'...
    '<li><i>-</i> : Decrease CLim</li>'...
    '<li><i>l</i> : Display/Edit Logbook</li>'...
    '<li><i>Crtl+s</i> : Save current bottom/regions to xml file</li>'...
    '</ul>'...
    '<ul>Modes :'...
    '<li><i>Normal mode</i> : Ctrl+right click : create a rectangle selection box, Shift+right click : create horizontal selection box</li>'...
    '<li><i>Bad Transmit Mode</i> : right click : set bad transmit, left click : remove bad transmit</li>'...
    '<li><i>Edit Bottom Mode</i> : right click : hand drawn bottom, left click : remove bottom, Shift+right click : segment creation bottom</li>'...
    '</ul>'...
    '<ul>Tips:'...
    '<li>Most objects (lines, regions, echograms...) have a context menu associated to them. Right-click and see!</li>'...
    '<li>You can grab the Mini Axes window by its side and drag it out</li>'...
    '<li>You can draw a zoom window in the mini axes, and drag it around...</li>'...
    '</ul></html>'];
jLabel = javaObjectEDT('javax.swing.JLabel',labelStr);
[jcomp,~] = javacomponent(jLabel,[0,25,500,775],dialog_fig);
bgcolor = num2cell(get(main_figure, 'Color'));
jcomp.setBackground(java.awt.Color(bgcolor{:}));
format_color_gui(dialog_fig,curr_disp.Font);

set(dialog_fig,'Visible','on');


end