function merged_reg=concatenate_regions_v2(regions)

if isempty(regions)
    merged_reg=[];
    return;
end

poly_union=regions(1).Poly;
for i=2:length(regions)
    poly_union=union(poly_union,regions(i).Poly);
end

if length(regions)>1
    shp='Rectangular';
else
    shp=regions.Shape;
end


merged_reg=region_cl(...
    'ID',regions(1).ID,...
    'Tag',regions(1).Tag,...
    'Name',regions(1).Name,...
    'Type','Data',...
    'Shape',shp,...
    'Poly',poly_union,...
    'Reference',regions(1).Reference,...
    'Cell_w',regions(1).Cell_w,...
    'Cell_w_unit',regions(1).Cell_w_unit,...
    'Cell_h',regions(1).Cell_h,...
    'Cell_h_unit',regions(1).Cell_h_unit);

end