function [fields,scale_fields,fmt_fields,factor_fields]=init_fields()

angle_fmt='int16';
angle_factor=1/500;

db_diff_fmt='int16';
db_diff_factor=1/500;

fish_fmt='uint16';
fish_factor=1/1000;

mot_comp_fmt='uint16';
mot_comp_factor=1/500;

db_fmt='uint16';
db_factor=-1/300;

lin_fmt='single';
lin_factor=1;

fields={'power','alongangle','acrossangle',...
    'sp','sv',...
    'powerunmatched','y_real','y_imag','spunmatched',...
    'powerdenoised','svdenoised','spdenoised','snr',...
    'singletarget',  'fishdensity', 'motioncompensation',...
    'acrossphi','alongphi' 'khz'};
scale_fields={'lin','angle','angle',...
    'db','db',...
    'lin','lin','lin','db',...
    'lin','db','db','db',...
    'db','density','db',...
    'angle','angle','db_diff'};
fmt_fields={lin_fmt angle_fmt angle_fmt...
    db_fmt db_fmt...
    lin_fmt lin_fmt lin_fmt db_fmt...   
    lin_fmt db_fmt db_fmt db_fmt...
    db_fmt fish_fmt mot_comp_fmt...
    angle_fmt angle_fmt db_diff_fmt};

factor_fields=[db_factor angle_factor angle_factor...
    db_factor db_factor...
    lin_factor lin_factor lin_factor db_factor...
    lin_factor db_factor db_factor db_factor...
    db_factor fish_factor mot_comp_factor...
    angle_factor angle_factor db_diff_factor];
