function createPingTable(dbconn)
ping_data_table=dbconn.fetch('select sql FROM sqlite_master WHERE type=''table'' AND name=''ping_data''');

if isempty(ping_data_table)
    createPingTable_str = ['create table ping_data ' ...
        '(Filename VARCHAR DEFAULT NULL,'...
        'Ping_number INTEGER DEFAULT NULL,',...
        'Frequency FLOAT DEFAULT NULL,',...
        'Lat FLOAT DEFAULT NULL,'...
        'Long FLOAT DEFAULT NULL,'...
        'Time TIME,'...%yyyy-mm-dd HH:MM:SS
        'Depth FLOAT DEFAULT NULL,'...
        'PRIMARY KEY (Filename,Ping_number,Frequency) ON CONFLICT REPLACE,'...
        'FOREIGN KEY(Filename) REFERENCES logbook(Filename))'];
    dbconn.exec(createPingTable_str);
end


