function load_multi_freq_tab(main_figure,parent_tab_group)

multi_freq_tab.parent_tab=uitab(parent_tab_group,'Title','Multi Freq','BackgroundColor','white');
multi_freq_tab.setting_panel=uipanel(multi_freq_tab.parent_tab,'Units','normalized','Position',[0 0 1 1]);
%multi_freq_tab.disp_panel=uipanel(multi_freq_tab.parent_tab,'Units','normalized','Position',[0.15 0 0.85 1]);


 uicontrol(...
'Parent',multi_freq_tab.setting_panel,...
'Units','normalized',...
'String','Primary Freq.',...
'Style','text',...
'Position',[0.05 0.9 0.15 0.1],...
'BackgroundColor','white',...
'Callback','');

multi_freq_tab.primary_freq = uicontrol(...
'Parent',multi_freq_tab.setting_panel,...
'Units','normalized',...
'String',{'--'},...
'Style','popupmenu',...
'Value',1,...
'Position',[0.05 0.8 0.15 0.1],...
'BackgroundColor','white',...
'Callback','',...
'Tag','primary_freq');

 uicontrol(...
'Parent',multi_freq_tab.setting_panel,...
'Units','normalized',...
'String','Secondary Freq.',...
'Style','text',...
'Position',[0.25 0.9 0.17 0.1],...
'BackgroundColor','white',...
'Callback','');

multi_freq_tab.secondary_freqs = uicontrol(...
'Parent',multi_freq_tab.setting_panel,...
'Units','normalized',...
'String',{'--'},...
'Style','listbox',...
'max',10,...
'Position',[0.25 0.4 0.15 0.5],...
'BackgroundColor','white',...
'Callback','',...
'Tag','secondary_freqs');

 uicontrol(...
'Parent',multi_freq_tab.setting_panel,...
'Units','normalized',...
'String','Sub-sampling',...
'Style','text',...
'Position',[0.45 0.9 0.15 0.1],...
'BackgroundColor','white',...
'Callback','');

multi_freq_tab.grid_pings=uicontrol(multi_freq_tab.setting_panel,'Style','edit','unit','normalized','position',[0.45 0.8 0.05 0.1],'string','5');
uicontrol(multi_freq_tab.setting_panel,'Style','Text','String','pings','units','normalized','Position',[0.5 0.8 0.15 0.1]);

multi_freq_tab.grid_samples=uicontrol(multi_freq_tab.setting_panel,'Style','edit','unit','normalized','position',[0.45 0.7 0.05 0.1],'string','5');
uicontrol(multi_freq_tab.setting_panel,'Style','Text','String','samples','units','normalized','Position',[0.5 0.7 0.15 0.1]);

set([multi_freq_tab.grid_pings multi_freq_tab.grid_samples],'callback',{@check_fmt_box,0,inf,5,'%.0f'})

 uicontrol(...
'Parent',multi_freq_tab.setting_panel,...
'Units','normalized',...
'String','dB Threshold',...
'Style','text',...
'Position',[0.45 0.6 0.15 0.1],...
'BackgroundColor','white',...
'Callback','');


multi_freq_tab.db_threshold=uicontrol(multi_freq_tab.setting_panel,'Style','edit','unit','normalized','position',[0.45 0.5 0.05 0.1],'string','-75');
uicontrol(multi_freq_tab.setting_panel,'Style','Text','String','dB','units','normalized','Position',[0.5 0.5 0.15 0.1]);

set(multi_freq_tab.db_threshold ,'callback',{@check_fmt_box,-999,-30,-75,'%.0f'})


uicontrol(...
    'Parent',multi_freq_tab.setting_panel,...
    'style','PushButton',...
    'String','Update',...
    'callback',{@compute_freq_diff_cback,main_figure},...
    'unit','normalized',...
    'position',[0.45 0.1 0.15 0.1]);

setappdata(main_figure,'multi_freq_tab',multi_freq_tab);
end

function compute_freq_diff_cback(src,evtdata,main_figure)

layer=getappdata(main_figure,'Layer');
curr_disp=getappdata(main_figure,'Curr_disp');
if isempty(layer)
    return;
end
multi_freq_tab=getappdata(main_figure,'multi_freq_tab');

primary_freq=str2double(multi_freq_tab.primary_freq.String(multi_freq_tab.primary_freq.Value,:));
secondary_freqs=cellstr(multi_freq_tab.secondary_freqs.String);
secondary_freqs=str2double(secondary_freqs(multi_freq_tab.secondary_freqs.Value));
secondary_freqs=setdiff(secondary_freqs,primary_freq);

if isempty(secondary_freqs)
    return;
end


[secondary_freqs,cax,~]=layer.generate_freq_differences('primary_freq',primary_freq,'secondary_freqs',secondary_freqs,...
    'Cell_h',str2double(multi_freq_tab.grid_samples.String),'Cell_w',str2double(multi_freq_tab.grid_pings.String),'sv_thr',str2double(multi_freq_tab.db_threshold.String));
if isempty(secondary_freqs)
    return;
end
curr_disp.ChannelID=layer.ChannelID{layer.Frequencies==primary_freq};
curr_disp.Freq=primary_freq;

curr_disp.setField(sprintf('Sv%.0fkHz',secondary_freqs(end)/1e3));
curr_disp.setCax(cax(end,:));
setappdata(main_figure,'Curr_disp',curr_disp);
update_display_tab(main_figure);

   
end