function initialize_display(main_figure)

axes_panel_comp.axes_panel=uipanel(main_figure,'Units','Normalized','Position',[0 0.05 1 .65],'BackgroundColor',[1 1 1],'tag','axes_panel');
axes_panel_comp.main_axes=axes('Parent',axes_panel_comp.axes_panel,'FontSize',10,'Units','normalized',...
    'Position',[0 0 1 1],...
    'Xlimmode','manual',...
    'Ylimmode','manual',...
    'XAxisLocation','bottom',...
    'TickDir','in',...
    'XTickLabel',{[]},...
    'YTickLabel',{[]},...
    'box','on',...
    'SortMethod','childorder',...
    'YDir','reverse',...
    'visible','off');

axes_panel_comp.vaxes=axes('Parent',axes_panel_comp.axes_panel,'FontSize',10,'Fontweight','Bold','Units','normalized',...
    'Position',[0 0 0 0],...
    'XAxisLocation','Top',...
    'YAxisLocation','right',...
    'TickLength',[0 0],...
    'visible','on',...
    'box','on',...
    'XTickLabel',{[]},...
    'Xgrid','on',...
    'Ygrid','on',...
    'GridColor',[0 0 0],...
    'YDir','reverse',...
    'visible','on');
hold on;
axes_panel_comp.v_axes_plot=plot(nan,'r');
axes_panel_comp.v_axes_text=text(nan,nan,'','Color','r','VerticalAlignment','bottom','fontsize',10);


axes_panel_comp.haxes=axes('Parent',axes_panel_comp.axes_panel,'FontSize',10,'Fontweight','Bold','Units','normalized',...
    'Position',[0 0 0 0],...
    'XAxisLocation','bottom',...
    'YAxisLocation','left',...
    'TickLength',[0 0],...
    'visible','on',...
    'box','on',...
    'YTickLabel',{[]},...
    'Xgrid','on',...
    'Ygrid','on',...
    'GridColor',[0 0 0],...
    'visible','on');
hold on;
axes_panel_comp.h_axes_plot=plot(nan,'k');
axes_panel_comp.h_axes_text=text(nan,nan,'','Color','r','VerticalAlignment','bottom','fontsize',10);

axes_panel_comp.colorbar=colorbar(axes_panel_comp.main_axes,'PickableParts','none','visible','off');

axes(axes_panel_comp.main_axes);
hold on;
axes_panel_comp.main_echo=imagesc(ones(1,1),'tag','echo');
axes_panel_comp.bottom_plot=plot(nan,'tag','bottom');
axes_panel_comp.track_plot=[];
axes_panel_comp.listeners=[];


info_panel_comp.info_panel=uipanel(main_figure,'Units','Normalized','Position',[0 0 1 .05],'BackgroundColor',[1 1 1],'tag','axes_panel');

setappdata(main_figure,'Axes_panel',axes_panel_comp);
setappdata(main_figure,'Info_panel',info_panel_comp);

set(main_figure,'Visible','on');
end



