function algo_vec=init_algos(r)

algo_bottom=algo_cl('Name','BottomDetection','Function',@detec_bottom_algo_v2,'Varargin',struct(...
    'denoised',0,...
    'thr_bottom',-35,...
    'thr_echo',-12,...
    'r_min',r(1),...
    'r_max',r(end)));

algo_bad_pings=algo_cl('Name','BadPings','Function',@bad_pings_removal_2,'Varargin',struct(...
    'denoised',0,...
    'thr_bottom',-35,...
    'thr_echo',-12,...
    'r_min',r(1),...
    'r_max',r(end),...
    'BS_std',6,...
    'BS_std_bool',true,...
    'thr_spikes_Above',3,...
    'thr_spikes_Below',3,...
    'Above',true,...
    'Below',false,...
    'burst_removal',false));

algo_denoise=algo_cl('Name','Denoise','Function',@bg_noise_removal_v2,'Varargin',struct(...
    'HorzFilt',50,...
    'VertFilt',r(end)/10,...
    'NoiseThr',-125,...
    'SNRThr',10));

algo_school_detect=algo_cl('Name','SchoolDetection','Function',@school_detect,'Varargin',struct(...
    'Type','Sv',...
    'Sv_thr',-65,...
    'l_min_can',10,...
    'h_min_tot',20,...
    'h_min_can',10,...
    'l_min_tot',50,...
    'nb_min_sples',100,...
    'horz_link_max',5,...
    'vert_link_max',5));

algo_single_target=algo_cl('Name','SingleTarget','Function',@single_targets_detection,'Varargin',struct(...
    'Type','Sp',...
    'TS_threshold',-65,...
    'PLDL',6,...
    'MinNormPL',0.6,...
    'MaxNormPL',1.5,...
    'MaxBeamComp',12,...
    'MaxStdMinAxisAngle',1,...
    'MaxStdMajAxisAngle',1));

algo_track_target=algo_cl('Name','TrackTarget','Function',@track_targets_angular,'Varargin',struct(...
'AlphaMajAxis',0.7,...
'AlphaMinAxis',0.7,...
'AlphaRange',0.7,...
'BetaMajAxis',0.5,...
'BetaMinAxis',0.5,...
'BetaRange',0.5,...
'ExcluDistMajAxis',1,...
'ExcluDistMinAxis',1,...
'ExcluDistRange',1,...
'MaxStdMajorAxisAngle',1,...
'MaxStdMinorAxisAngle',1,...
'MissedPingExpMajAxis',5,...
'MissedPingExpMinAxis',5,...
'MissedPingExpRange',5,...
'WeightMajAxis',20,...
'WeightMinAxis',20,...
'WeightRange',40,...
'WeightTS',10,...
'WeightPingGap',10,...
'Min_ST_Track',8,...
'Min_Pings_Track',10,...
'Max_Gap_Track',5));



algo_vec=[algo_bottom algo_bad_pings algo_denoise algo_school_detect algo_single_target algo_track_target];

end