function update_algos(main_figure)

layer=getappdata(main_figure,'Layer');
curr_disp=getappdata(main_figure,'Curr_disp');
idx_freq=find_freq_idx(layer,curr_disp.Freq);

Transceiver=layer.Transceivers(idx_freq);
f_s_sig=round(1/(Transceiver.Params.SampleInterval(1)));
c=(layer.EnvData.SoundSpeed);


bottom_tab_comp=getappdata(main_figure,'Bottom_tab');
bad_ping_tab_comp=getappdata(main_figure,'Bad_ping_tab');
school_detect_tab_comp=getappdata(main_figure,'School_detect_tab');
denoise_tab_comp=getappdata(main_figure,'Denoise_tab');
single_target_tab_comp=getappdata(main_figure,'Single_target_tab');

track_target_tab_comp=getappdata(main_figure,'Track_target_tab');



[idx_algo_denoise,found_denoise]=find_algo_idx(layer.Transceivers(idx_freq),'Denoise');
[idx_algo_bot,found_bot]=find_algo_idx(layer.Transceivers(idx_freq),'BottomDetection');
[idx_algo_bp,found_bp]=find_algo_idx(layer.Transceivers(idx_freq),'BadPings');
[idx_school_detect,found_school]=find_algo_idx(layer.Transceivers(idx_freq),'SchoolDetection');
[idx_single_target,found_single]=find_algo_idx(layer.Transceivers(idx_freq),'SingleTarget');
[idx_track_target,found_track]=find_algo_idx(layer.Transceivers(idx_freq),'TrackTarget');

if found_bot>0
    layer.Transceivers(idx_freq).Algo(idx_algo_bot).Varargin=struct('thr_bottom',get(bottom_tab_comp.Thr_bottom_sl,'Value'),...
        'denoised',get(bottom_tab_comp.denoised,'Value'),...
        'thr_echo',get(bottom_tab_comp.Thr_echo_sl,'Value'),...
        'r_min',get(bottom_tab_comp.r_min_sl,'Value'),...
        'r_max',get(bottom_tab_comp.r_max_sl,'Value'));
end


if found_bp>0
    layer.Transceivers(idx_freq).Algo(idx_algo_bp).Varargin=struct(...
        'denoised',get(bottom_tab_comp.denoised,'Value'),...
        'thr_bottom',get(bad_ping_tab_comp.Thr_bottom_sl,'Value'),...
        'thr_echo',get(bad_ping_tab_comp.Thr_echo_sl,'Value'),...
        'r_min',get(bad_ping_tab_comp.r_min_sl,'Value'),...
        'r_max',get(bad_ping_tab_comp.r_max_sl,'Value'),...
        'BS_std',get(bad_ping_tab_comp.BS_std_sl,'Value'),...
        'BS_std_bool',get(bad_ping_tab_comp.BS_std_bool,'Value')==1,...
        'thr_spikes_Above',get(bad_ping_tab_comp.thr_spikes_Above_sl,'Value'),...
        'thr_spikes_Below',get(bad_ping_tab_comp.thr_spikes_Below_sl,'Value'),...
        'Above',get(bad_ping_tab_comp.Above,'Value')==1,...
        'Below',get(bad_ping_tab_comp.Below,'Value')==1,...
        'burst_removal',false);
end

if found_school>0
    Type=layer.Transceivers(idx_freq).Algo(idx_school_detect).Varargin.Type;
    layer.Transceivers(idx_freq).Algo(idx_school_detect).Varargin=struct(...
        'Type',Type,....
        'Sv_thr',get(school_detect_tab_comp.sv_thr_sl,'Value'),...
        'l_min_can',get(school_detect_tab_comp.l_min_can_sl,'Value'),...
        'h_min_tot',get(school_detect_tab_comp.h_min_tot_sl,'Value'),...
        'h_min_can',get(school_detect_tab_comp.h_min_can_sl,'Value'),...
        'l_min_tot',get(school_detect_tab_comp.l_min_tot_sl,'Value'),...
        'nb_min_sples',get(school_detect_tab_comp.nb_min_sples_sl,'Value'),...
        'horz_link_max',get(school_detect_tab_comp.horz_link_max_sl,'Value'),...
        'vert_link_max',get(school_detect_tab_comp.vert_link_max_sl,'Value'));
end



if found_denoise>0
    layer.Transceivers(idx_freq).Algo(idx_algo_denoise).Varargin=struct(...
        'SNRThr',round(get(denoise_tab_comp.SNRThr_sl,'Value')),...
        'HorzFilt',get(denoise_tab_comp.HorzFilt_sl,'Value'),...
        'VertFilt',round(get(denoise_tab_comp.VertFilt_sl,'Value')),...
        'NoiseThr',round(get(denoise_tab_comp.NoiseThr_sl,'Value')));
end

if found_single>0
    if isfield(bottom_tab_comp,'denoised')
        if get(bottom_tab_comp.denoised,'Value')>0
            Type='SpDenoised';
        else
            Type='Sp';
        end
    else
        Type='Sp';
    end
    
    layer.Transceivers(idx_freq).Algo(idx_single_target).Varargin=struct(...
        'Type',Type,...
        'TS_threshold',get(single_target_tab_comp.TS_threshold_sl,'Value'),...
        'PLDL',get(single_target_tab_comp.PLDL_sl,'Value'),...
        'MinNormPL',get(single_target_tab_comp.MinNormPL_sl,'Value'),...
        'MaxNormPL',get(single_target_tab_comp.MaxNormPL_sl,'Value'),...
        'MaxBeamComp',get(single_target_tab_comp.MaxBeamComp_sl,'Value'),...
        'MaxStdMinAxisAngle',get(single_target_tab_comp.MaxStdMinAxisAngle_sl,'Value'),...
        'MaxStdMajAxisAngle',get(single_target_tab_comp.MaxStdMajAxisAngle_sl,'Value'));
end

if found_track
layer.Transceivers(idx_freq).Algo(idx_track_target).Varargin=struct(...
 'AlphaMajAxis',str2double(get(track_target_tab_comp.AlphaMajAxis,'string')),...
        'AlphaMinAxis',str2double(get(track_target_tab_comp.AlphaMinAxis,'string')),...
        'AlphaRange',str2double(get(track_target_tab_comp.AlphaRange,'string')),...
        'BetaMajAxis',str2double(get(track_target_tab_comp.BetaMajAxis,'string')),...
        'BetaMinAxis',str2double(get(track_target_tab_comp.BetaMinAxis,'string')),...
        'BetaRange',str2double(get(track_target_tab_comp.BetaRange,'string')),...
        'ExcluDistMajAxis',str2double(get(track_target_tab_comp.ExcluDistMajAxis,'string')),...
        'ExcluDistMinAxis',str2double(get(track_target_tab_comp.ExcluDistMinAxis,'string')),...
        'ExcluDistRange',str2double(get(track_target_tab_comp.ExcluDistRange,'string')),...
        'MaxStdMinorAxisAngle',str2double(get(track_target_tab_comp.MaxStdMinorAxisAngle,'string')),...
        'MaxStdMajorAxisAngle',str2double(get(track_target_tab_comp.MaxStdMajorAxisAngle,'string')),...
        'MissedPingExpMajAxis',str2double(get(track_target_tab_comp.MissedPingExpMajAxis,'string')),...
        'MissedPingExpMinAxis',str2double(get(track_target_tab_comp.MissedPingExpMinAxis,'string')),...
        'MissedPingExpRange',str2double(get(track_target_tab_comp.MissedPingExpRange,'string')),...
        'WeightMajAxis',str2double(get(track_target_tab_comp.WeightMajAxis,'string')),...
        'WeightMinAxis',str2double(get(track_target_tab_comp.WeightMinAxis,'string')),...
        'WeightRange',str2double(get(track_target_tab_comp.WeightRange,'string')),...
        'WeightTS',str2double(get(track_target_tab_comp.WeightTS,'string')),...
        'WeightPingGap',str2double(get(track_target_tab_comp.WeightPingGap,'string')),...
        'Min_ST_Track',str2double(get(track_target_tab_comp.Min_ST_Track,'string')),...
        'Min_Pings_Track',str2double(get(track_target_tab_comp.Min_Pings_Track,'string')),...
        'Max_Gap_Track',str2double(get(track_target_tab_comp.Max_Gap_Track,'string')));
end
    
    
setappdata(main_figure,'Layer',layer);


end