function layer_out=concatenate_layers(layer_1,layer_2)

newname=[layer_1.Filename layer_2.Filename];


layer_out=layer_cl('Filename',newname,...
    'Filetype',layer_1.Filetype,...
    'PathToFile',layer_1.PathToFile,...
    'Transceivers',concatenate_Transceivers(layer_1.Transceivers,layer_2.Transceivers),...
    'AttitudeNav',concatenate_AttitudeNavPing(layer_1.AttitudeNav,layer_2.AttitudeNav),...
    'GPSData',concatenate_GPSData(layer_1.GPSData,layer_2.GPSData),...
    'SurveyData',layer_1.get_survey_data(),...
    'Frequencies',layer_1.Frequencies);
clear layer_1 layer_2;

end